# Skelly-Jelly Workspace Dependencies Catalog
# Central version management for all workspace dependencies
# Last updated: 2024-01-27

[versions]
# Async runtime
tokio = "1.40"
tokio-stream = "0.1"
async-trait = "0.1"

# Core utilities
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"

# Data structures
uuid = { version = "1.11", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
bytes = "1.5"

# Concurrency
dashmap = "6.0"
parking_lot = "0.12"
crossbeam-channel = "0.5"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Testing
mockall = "0.13"
tempfile = "3.14"
test-log = "0.2"
tokio-test = "0.4"
criterion = "0.5"
proptest = "1.4"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "migrate", "chrono", "uuid"] }

# Compression
lz4 = "1.24"
zstd = "0.13"

# Metrics
prometheus = "0.13"
sysinfo = "0.30"

# Serialization
bincode = "1.3"
prost = "0.12"

# Performance
rayon = "1.8"
lru = "0.12"

# Image processing
image = { version = "0.24", features = ["png", "webp"] }
imageproc = "0.23"

# ML/AI
candle-core = "0.3"
candle-nn = "0.3"
candle-transformers = "0.3"
tokenizers = "0.15"

# HTTP/Web
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
axum = "0.7"

# CLI
clap = { version = "4.0", features = ["derive"] }

[usage]
# Example usage in module Cargo.toml:
# [dependencies]
# tokio = { workspace = true }
# serde = { workspace = true }
# dashmap = { workspace = true }

[notes]
# 1. All modules should reference versions from this catalog
# 2. Update this file when adding new dependencies
# 3. Run dependency check script before commits
# 4. Version updates should be coordinated across all modules